apiVersion: apps/v1
kind: Deployment
metadata:
  name: kittyapp
spec:
  selector:
    matchLabels:
      templatename: kittytemplate
  template:
    metadata:
      labels:
        templatename: kittytemplate
    spec:
      containers:
        - image: rnogowski/test:0.1
          name: tdo-btp-hello-world      